version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    container_name: lab6_clickhouse
    ports:
      - "8123:8123"
    environment:
      - CLICKHOUSE_DB=weather
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: