version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis
      - elasticsearch
      - clickhouse

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"

  redis:
    image: redis:7
    container_name: lab6_redis
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: lab6_elastic
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"

  clickhouse:
    image: clickhouse/clickhouse-server:24
    container_name: lab6_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
  redis_data:
  ch_data:
  es_data: